# Generated by Django 5.1 on 2025-05-20 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produit_prix_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='justification_prix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='prix_initial_fcfa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandepartenaire',
            name='justification_prix',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commandepartenaire',
            name='prix_initial_fcfa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='modele',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='processeur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='stockage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='systeme_exploitation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('vente', 'Vente'), ('achat', 'Achat'), ('retour', 'Retour')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boutique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['-date_operation'],
            },
        ),
    ]
