# Generated by Django 5.1 on 2025-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_produit_options_produit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='annee',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modele',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='processeur',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ram',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stockage',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='systeme_exploitation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
