# Generated by Django 5.1 on 2025-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_produit_annee_alter_produit_marque_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['date_operation'], name='core_journa_date_op_a99831_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['type_operation'], name='core_journa_type_op_fb3912_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['utilisateur'], name='core_journa_utilisa_417e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['boutique'], name='core_journa_boutiqu_2c0bfa_idx'),
        ),
    ]
