# Generated by Django 5.1 on 2025-09-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_debt_debtpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boutique',
            options={'ordering': ['nom'], 'verbose_name': 'Boutique', 'verbose_name_plural': 'Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='commandeclient',
            options={'verbose_name': 'Commande client', 'verbose_name_plural': 'Commandes client'},
        ),
        migrations.AlterModelOptions(
            name='commandepartenaire',
            options={'verbose_name': 'Commande partenaire', 'verbose_name_plural': 'Commandes partenaire'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='historiquestock',
            options={'ordering': ['-date'], 'verbose_name': 'Historique de stock', 'verbose_name_plural': 'Historiques de stock'},
        ),
        migrations.AlterModelOptions(
            name='partenaire',
            options={'ordering': ['-dateadhesion', 'nom'], 'verbose_name': 'Partenaire', 'verbose_name_plural': 'Partenaires'},
        ),
        migrations.AlterModelOptions(
            name='prixproduit',
            options={'ordering': ['-date'], 'verbose_name': 'Prix produit', 'verbose_name_plural': 'Prix produits'},
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='versement',
            options={'ordering': ['-date_versement'], 'verbose_name': 'Versement', 'verbose_name_plural': 'Versements'},
        ),
        migrations.RenameIndex(
            model_name='debt',
            new_name='core_debt_status_971140_idx',
            old_name='core_debt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='debt',
            new_name='core_debt_technic_38aa83_idx',
            old_name='core_debt_technician_idx',
        ),
        migrations.RenameIndex(
            model_name='debt',
            new_name='core_debt_created_2b1cd2_idx',
            old_name='core_debt_created_idx',
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='commandepartenaire',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_partenaire', to='core.facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='historiquestock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_stock', to='core.produit'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='type_operation',
            field=models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='localisation',
            field=models.CharField(blank=True, default='Bafoussam', max_length=100),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='statut',
            field=models.CharField(choices=[('encours', 'En cours'), ('paye', 'Payé')], default='encours', max_length=20),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='prixproduit',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prix_detail', to='core.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('ordinateur', 'Ordinateur'), ('accessoire', 'Accessoire'), ('ecran', 'Ecran'), ('imprimante', 'Imprimante'), ('tablette', 'Tablette'), ('casque', 'Casque'), ('clavier', 'Clavier'), ('souris', 'Souris'), ('modem', 'Modem'), ('disquedur', 'Disque dur'), ('cleusb', 'Clé USB'), ('autre', 'Autre')], default='ordinateur', max_length=20),
        ),
        migrations.AlterField(
            model_name='versement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='core.facture'),
        ),
    ]
