# Generated by Django 5.1 on 2025-09-29 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_boutique_options_alter_commandeclient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='contrat_confidentialite',
            field=models.BooleanField(default=False, help_text='Contrat de confidentialité inclus'),
        ),
        migrations.AddField(
            model_name='facture',
            name='garantie',
            field=models.PositiveIntegerField(default=1, help_text='Garantie en mois (1-10)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('ordinateur', 'Ordinateur'), ('telephone', 'Téléphone'), ('accessoire', 'Accessoire'), ('ecran', 'Ecran'), ('imprimante', 'Imprimante'), ('tablette', 'Tablette'), ('casque', 'Casque'), ('clavier', 'Clavier'), ('souris', 'Souris'), ('modem', 'Modem'), ('disquedur', 'Disque dur'), ('cleusb', 'Clé USB'), ('autre', 'Autre')], default='ordinateur', max_length=20),
        ),
    ]
